### ISSUE TITLE
Not working with react-scripts 5.0.0

### ISSUE THREAD

**Issue by ikamaru** [APIs-guru/create-react-app-redoc#20]
I tried to run this project with react-scripts 5.0.0 and encountered the issues below, but it works fine with 4.0.3.
(could you please support this version of react-scripts 🙏)

```
Compiled with problems:X

ERROR in ./node_modules/@redocly/openapi-core/lib/config/config.js 10:13-28

Module not found: Error: Can't resolve 'path' in '.../node_modules/@redocly/openapi-core/lib/config'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }


ERROR in ./node_modules/@redocly/openapi-core/lib/redocly/index.js 42:15-30

Module not found: Error: Can't resolve 'path' in '.../node_modules/@redocly/openapi-core/lib/redocly'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }


etc...
```

**Comment by RomanHotsiy** [comment]
You should follow suggestions from the error message and provide a fallback.

Also, this should be resolved on the latest version of redoc.

**Comment by TeemuKurki** [comment]
We cannot provide a fallback because react-scripts hides webpack configurations from us.
When using react-scripts (create-react-app) configurations (webpack, babel, etc) are hidden from us and we cannot modify them without ejecting the whole application, which defeats the whole purpose of react-script. There are tools like craco that we can use to inject webpack configurations into react-scripts, but they are still working on react-script 5 support.

At this moment we cannot use latest major version of react-scripts with Redoc.
